version: '3'

services:
  bot:
    build: .
    command: python3 -O main.py
    container_name: rei-bot
    depends_on:
      - db
      - lavalink
    ports:
      - "59076:59076"
    restart: unless-stopped
    dns:
      - 76.76.2.2
      - 76.76.10.2

  db:
    container_name: rei-db
    environment:
      - POSTGRES_DB=rei
      - POSTGRES_PASSWORD=pN3PqpT86Nfr
      - POSTGRES_USER=rei
    image: postgres:alpine
    expose:
      - "5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data

  lavalink:
    container_name: rei-lavalink
    environment:
      - _JAVA_OPTIONS=-Xmx8G
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
      - SERVER_PORT=2333
    image: ghcr.io/lavalink-devs/lavalink:4
    expose:
      - "2333"
    restart: unless-stopped

volumes:
  data:
